objects/PricingEvent__e/PricingEvent__e.object-meta.xml
<CustomObject>
    <label>Pricing Event</label>
    <pluralLabel>Pricing Events</pluralLabel>
</CustomObject>

objects/PricingEvent__e/fields/CustomerId__c.field-meta.xml
<CustomField>
    <fullName>CustomerId__c</fullName>
    <label>CustomerId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

objects/PricingEvent__e/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

classes/DiscountComponentController.cls
public without sharing class DiscountComponentController {
    
    @AuraEnabled
    public static void checkDiscount(String params){
        try {
            Map<String,Object> paramsMap = (Map<String,Object>)System.JSON.deserializeUntyped(params);
            PricingEvent__e event =  new PricingEvent__e();
            event.CustomerId__c = (String)paramsMap.get('customerId');
            event.Location__c   = (String)paramsMap.get('countryCode');
            Eventbus.publish(event);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}